language: csharp
dotnet: 2.0.0
mono:
 -latest
matrix:
  include:
    - os: linux
      dist: trusty      
      sudo: false
    - os: osx
      osx_image: xcode9      
      sudo: required               
script:  
  - ulimit -n8192  
  - chmod +x build.sh
  - ./build.sh