language: csharp
matrix:
  include:
    - os: osx
      osx_image: xcode9      
      sudo: required      
      dotnet: 2.0.0    
before_install:
  - brew update
install:
  - ulimit -n4096  
script:  
  - dotnet test src/Dotnet.Script.Tests/Dotnet.Script.Tests.csproj